# action.yml
name: 'cPanel Action'
description: 'This is a test action for cPanel'
inputs:
  cpanel-username:  # id of input
    description: 'username'
    required: true
    default: 'username'
  cpanel-token:  # id of input
    description: 'token'
    required: true
    default: 'token'
  cpanel-hostname:  # id of input
    description: 'hostname'
    required: true
    default: 'hostname'
#outputs:
#  time: # id of output
#    description: 'The time app deployed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cpanel-username }}
    - ${{ inputs.cpanel-token }}
    - ${{ inputs.cpanel-hostname }}
