# action.yml
name: 'cPanel Action'
description: 'This is a test action for cPanel'
inputs:
  test-input:  # id of input
    description: 'test input'
    required: true
    default: 'This is a test'
outputs:
  time: # id of output
    description: 'The time app deployed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-input }}
